# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  # Categories: /categories
  About: /about/

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  search: true
  navbar: true 
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode: 
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: wrodbeyondyoung@gmail.com
  # stack-overflow:
  # twitter:
  # facebook:
  # linkedin:
  # google:
  github: https://github.com/buginux
  weibo: http://weibo.com/swiftyper
  # zhihu: 
  jianshu: http://www.jianshu.com/users/3b40e55ec6d5/latest_articles

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 7a71baaea5cb77555879cfaf4b521328
# Google Analytics
google_analytics: UA-70950925-1

# Duoshuo
# duoshuo_shortname: 
# Disqus
disqus_shortname: swiftyper


# ===========================================
# Version
# ===========================================
version: 2.2.x