# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  # Categories: /categories
  About: /about/

# site search option
search: true

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# ===========================================
# Social links Settings
# ===========================================
social:
  email: mailto:wordbeyondyoung@gmail.com
#  stack-overflow:
#  twitter:
#  facebook:
  github: https://github.com/buginux
  weibo: http://weibo.com/swiftyper
  jianshu: http://www.jianshu.com/users/3b40e55ec6d5/latest_articles
#  zhihu:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 7a71baaea5cb77555879cfaf4b521328
# Google Analytics
google_analytics: UA-70950925-1

# Duoshuo
# duoshuo_shortname: 
# Disqus
disqus_shortname: swiftyper


# ===========================================
# Version
# ===========================================
version: 2.1.0
